/*
    * Copyright (C) 2013 Developed by reg <entry.reg@gmail.com>
    *
    * Licensed under the Apache License, Version 2.0 (the "License");
    * you may not use this file except in compliance with the License.
    * You may obtain a copy of the License at
    *
    *      http://www.apache.org/licenses/LICENSE-2.0
    *
    * Unless required by applicable law or agreed to in writing, software
    * distributed under the License is distributed on an "AS IS" BASIS,
    * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    * See the License for the specific language governing permissions and
    * limitations under the License.
 */

package reg.util.dc.flylink.renamer;

import java.awt.event.ActionListener;
import javax.swing.text.BadLocationException;

/**
 *
 * @author reg
 */
public class MainForm extends javax.swing.JFrame
{
    private boolean firstClickedOnListFiles = false;
    
    /**
     * Creates new form MainForm
     */
    public MainForm()
    {
        setLookAndFeel();
        initComponents();
        this.setLocationRelativeTo(null); //to center screen
    }
    
    /**
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * details: http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    private void setLookAndFeel()
    {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch(Exception e){}
    }
    
    /**
     * Set handler for component btnRenameInDb
     * @param l 
     */    
    protected void listnerRenameInDb(ActionListener l)
    {
        btnRenameInDb.addActionListener(l);
    }
    
    /**
     * Text line by number
     * @param n line number
     * @return
     * @throws IndexOutOfBoundsException 
     */
    public String getLineFromListFiles(int n) throws IndexOutOfBoundsException
    {
        try{
            int offsetStart = listFiles.getLineStartOffset(n);
            int offsetEnd   = listFiles.getLineEndOffset(n);
            return listFiles.getText(offsetStart, offsetEnd - offsetStart);
        }
        catch(BadLocationException e){
            throw new IndexOutOfBoundsException("value (" + n + ") out of range. " + e.getMessage());
        }
    }
    
    public int getCountListFilesLines()
    {
        return listFiles.getLineCount();
    }
    
    public void renderVersionApp(String v)
    {
        this.setTitle(v + " " + this.getTitle());
    }
    
    /**
     * Добавляет текст в начало указанной строки.
     * @param n line number
     * @param text
     */
    public void appendListFilesBeforeLine(int n, String text) throws IndexOutOfBoundsException
    {
        try{
            int offset = listFiles.getLineStartOffset(n);         
            listFiles.replaceRange(text, offset, offset);
        }
        catch(BadLocationException e){
            throw new IndexOutOfBoundsException("value (" + n + ") out of range. " + e.getMessage());
        }        
    }
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        listFiles = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnRenameInDb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Патч переименования путей для FlylinkDC++");

        listFiles.setColumns(20);
        listFiles.setRows(5);
        listFiles.setText("Формат:\nСтарый путь > Новый Путь\nСтарый путь > Новый Путь\n...\n\n#Примеры:\n\n  Директории:\n     # D:\\folder 1\\sub1\\   > D:\\Picture\\Cars\\\n     # D:/folder 2/             > E:/Movies/\n\n  Файлы:\n    # E:\\dir1\\w1.mkv      > E:\\dir1\\warm water.mkv\n    # e:/dir1/175.png     > f:/bigcat.png                   # Временно заглушка: ERROR-NEWPATH\n    # e:\\dir1\\header       > f:\\header.cfg                  # Временно заглушка: ERROR-NEWPATH\n\nПометки о выполнении:\n   [OK]:         Успешно выполнено текущая строка\n   [ERROR-???]:  Неправильный формат текущей строки");
        listFiles.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                listFilesMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                listFilesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listFiles);

        btnRenameInDb.setText("Переимновать в БД");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnRenameInDb)
                .addGap(0, 626, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRenameInDb)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Патч переименования путей для FlylinkDC++");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listFilesMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_listFilesMouseClicked
    {//GEN-HEADEREND:event_listFilesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listFilesMouseClicked

    private void listFilesMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_listFilesMouseReleased
    {//GEN-HEADEREND:event_listFilesMouseReleased
        // TODO add your handling code here:
        if(!firstClickedOnListFiles){
            listFiles.setText("");
            firstClickedOnListFiles = true;
        }        
    }//GEN-LAST:event_listFilesMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRenameInDb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea listFiles;
    // End of variables declaration//GEN-END:variables
}
