/*
    * Copyright (C) 2013 Developed by reg <entry.reg@gmail.com>
    *
    * Licensed under the Apache License, Version 2.0 (the "License");
    * you may not use this file except in compliance with the License.
    * You may obtain a copy of the License at
    *
    *      http://www.apache.org/licenses/LICENSE-2.0
    *
    * Unless required by applicable law or agreed to in writing, software
    * distributed under the License is distributed on an "AS IS" BASIS,
    * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    * See the License for the specific language governing permissions and
    * limitations under the License.
 */

package reg.util.dc.flylink.renamer;

import java.awt.event.ActionListener;
import javax.swing.text.BadLocationException;

/**
 *
 * @author reg
 */
public class MainForm extends javax.swing.JFrame
{
    private boolean firstClickedOnListFiles = false;
    
    /**
     * Creates new form MainForm
     */
    public MainForm()
    {
        setLookAndFeel();
        initComponents();
        listFiles.setComponentPopupMenu(menuMain);
        this.setLocationRelativeTo(null); //to center screen
    }
    
    /**
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * details: http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    private void setLookAndFeel()
    {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch(Exception e){}
    }
    
    /**
     * Set handler for component btnRenameInDb
     * @param l 
     */    
    protected void listnerRenameInDb(ActionListener l)
    {
        btnRenameInDb.addActionListener(l);
    }
    
    protected void listnerLogOpen(ActionListener l)
    {
        btnLogOpen.addActionListener(l);
    }
    
    /**
     * Text line by number
     * @param n line number
     * @return
     * @throws IndexOutOfBoundsException 
     */
    public String getLineFromListFiles(int n) throws IndexOutOfBoundsException
    {
        try{
            int offsetStart = listFiles.getLineStartOffset(n);
            int offsetEnd   = listFiles.getLineEndOffset(n);
            return listFiles.getText(offsetStart, offsetEnd - offsetStart);
        }
        catch(BadLocationException e){
            throw new IndexOutOfBoundsException("value (" + n + ") out of range. " + e.getMessage());
        }
    }
    
    public int getCountListFilesLines()
    {
        return listFiles.getLineCount();
    }
    
    public void renderVersionApp(String v)
    {
        this.setTitle(v + " " + this.getTitle());
    }
    
    public boolean isCheckReverseRename()
    {
        return chkReverseRename.isSelected();
    }
    
    /**
     * Добавляет текст в начало указанной строки.
     * @param n line number
     * @param text
     */
    public void appendListFilesBeforeLine(int n, String text) throws IndexOutOfBoundsException
    {
        try{
            int offset = listFiles.getLineStartOffset(n);         
            listFiles.replaceRange(text, offset, offset);
        }
        catch(BadLocationException e){
            throw new IndexOutOfBoundsException("value (" + n + ") out of range. " + e.getMessage());
        }        
    }
    
    private void listClear()
    {
        listFiles.setText("");
    }    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        menuMain = new javax.swing.JPopupMenu();
        menuCopy = new javax.swing.JMenuItem();
        menuCut = new javax.swing.JMenuItem();
        menuPaste = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuClear = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFiles = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnRenameInDb = new javax.swing.JButton();
        btnLogOpen = new javax.swing.JButton();
        chkReverseRename = new javax.swing.JCheckBox();

        menuCopy.setText("Копировать");
        menuCopy.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                menuCopyActionPerformed(evt);
            }
        });
        menuMain.add(menuCopy);

        menuCut.setText("Вырезать");
        menuCut.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                menuCutActionPerformed(evt);
            }
        });
        menuMain.add(menuCut);

        menuPaste.setText("Вставить");
        menuPaste.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                menuPasteActionPerformed(evt);
            }
        });
        menuMain.add(menuPaste);
        menuMain.add(jSeparator1);

        menuClear.setText("Очистить");
        menuClear.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                menuClearActionPerformed(evt);
            }
        });
        menuMain.add(menuClear);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Патч переименования путей для FlylinkDC++");

        listFiles.setColumns(20);
        listFiles.setRows(5);
        listFiles.setText("Формат:\nСтарый путь > Новый Путь\nСтарый путь > Новый Путь\n...\n\n#Примеры:\n\n  Директории:\n     # D:\\folder 1\\sub1\\   > D:\\Picture\\Cars\\\n     # D:/folder 2/             > E:/Movies/\n\n  Файлы:\n    # E:\\dir1\\w1.mkv      > E:\\dir1\\warm water.mkv\n    # e:/dir1/175.png     > f:/bigcat.png   \n    # e:\\dir1\\header       > f:\\header.cfg  \n\nПометки о выполнении:\n   [OK]:         Успешно выполнено текущая строка\n   [ERROR-???]:  Неправильный формат текущей строки");
        listFiles.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                listFilesMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(listFiles);

        btnRenameInDb.setText("Переимновать в БД");

        btnLogOpen.setText("Открыть лог");

        chkReverseRename.setText("Обратное переименование");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnRenameInDb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkReverseRename)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogOpen)
                .addGap(0, 350, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnRenameInDb)
                .addComponent(btnLogOpen)
                .addComponent(chkReverseRename))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Патч переименования путей для FlylinkDC++");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listFilesMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_listFilesMouseReleased
    {//GEN-HEADEREND:event_listFilesMouseReleased
        if(!firstClickedOnListFiles){
            listClear();
            firstClickedOnListFiles = true;
        }
    }//GEN-LAST:event_listFilesMouseReleased

    private void menuCopyActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menuCopyActionPerformed
    {//GEN-HEADEREND:event_menuCopyActionPerformed
        listFiles.copy();
    }//GEN-LAST:event_menuCopyActionPerformed

    private void menuCutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menuCutActionPerformed
    {//GEN-HEADEREND:event_menuCutActionPerformed
        listFiles.cut();
    }//GEN-LAST:event_menuCutActionPerformed

    private void menuPasteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menuPasteActionPerformed
    {//GEN-HEADEREND:event_menuPasteActionPerformed
        listFiles.paste();
    }//GEN-LAST:event_menuPasteActionPerformed

    private void menuClearActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menuClearActionPerformed
    {//GEN-HEADEREND:event_menuClearActionPerformed
        listClear();
    }//GEN-LAST:event_menuClearActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOpen;
    private javax.swing.JButton btnRenameInDb;
    private javax.swing.JCheckBox chkReverseRename;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea listFiles;
    private javax.swing.JMenuItem menuClear;
    private javax.swing.JMenuItem menuCopy;
    private javax.swing.JMenuItem menuCut;
    private javax.swing.JPopupMenu menuMain;
    private javax.swing.JMenuItem menuPaste;
    // End of variables declaration//GEN-END:variables
}
